Repository rainclouded/Concierge, pull requests merged in 2024-10, with the labels that each got.

#128 Readme update/81594494
  Docs/Sprint0/images/block_diagram.jpg
  Docs/Sprint0/sprint_0_worksheet.md
  Docs/images/logo.png
  Docs/project-technical-details.md
  README.md
Labels: documentation

#142 Guest UI (Login, HomePage, Amenities, Incident report
  src/guest_webapp/.env
  src/guest_webapp/.gitignore
  src/guest_webapp/cypress.config.js
  src/guest_webapp/cypress/components/AmenitiesPage.cy.jsx
  src/guest_webapp/cypress/components/HomePage.cy.jsx
  src/guest_webapp/cypress/e2e/integration_test.cy.js
  src/guest_webapp/cypress/fixtures/example.json
  src/guest_webapp/cypress/support/commands.js
  src/guest_webapp/cypress/support/component-index.html
  src/guest_webapp/cypress/support/component.js
  src/guest_webapp/cypress/support/e2e.js
  src/guest_webapp/package-lock.json
  src/guest_webapp/package.json
  src/guest_webapp/src/App.jsx
  src/guest_webapp/src/components/ServiceCard.jsx
  src/guest_webapp/src/main.jsx
  src/guest_webapp/src/pages/AmenitiesPage.jsx
  src/guest_webapp/src/pages/HomePage.jsx
  src/guest_webapp/src/pages/IncidentReportPage.jsx
  src/guest_webapp/src/pages/LoginPage.jsx
Labels: Dev task

#147 Fixed bug when creating new amenities and incident reports on staff ui
  src/staff_webapp/src/app/components/amenity-form/amenity-form.component.ts
  src/staff_webapp/src/app/components/incident-report-form/incident-report-form.component.css
  src/staff_webapp/src/app/components/incident-report-form/incident-report-form.component.ts
  src/staff_webapp/src/app/pages/incident-reports-tab/incident-reports-tab.component.css
  src/staff_webapp/src/app/pages/incident-reports-tab/incident-reports-tab.component.ts
  src/staff_webapp/src/app/pages/login-page/login-page.component.css
  src/staff_webapp/src/app/pages/login-page/login-page.component.ts
Labels: bug

#165 Dev task/test amenity db integration/84008885
  src/amenities/README.md
  src/amenities/amenities.sln
  src/amenities/amenities_db_integration_test/DbInterfaceTests.cs
  src/amenities/amenities_db_integration_test/EndpointIntegrationTests.cs
  src/amenities/amenities_db_integration_test/WebAppFactoryForTests.cs
  src/amenities/amenities_db_integration_test/amenities_integration_test.csproj
  src/amenities/amenities_server/Program.cs
  src/amenities/amenities_server/application/Services.cs
  src/amenities/amenities_server/controller/AmenitiesController.cs
  src/amenities/amenities_server/model/Amenity.cs
  src/amenities/amenities_server/model/AmenityResponse.cs
  src/amenities/amenities_server/model/ResponseMessages.cs
  src/amenities/amenities_server/persistence/IAmenityPersistence.cs
  src/amenities/amenities_server/persistence/PostgresAmenityPersistence.cs
  src/amenities/amenities_server/persistence/StubAmenityPersistence.cs
  src/amenities/amenities_server/validators/AmenityValidator.cs
  src/amenities/amenities_server/validators/IPermissionValidator.cs
  src/amenities/amenities_test/UnitTest1.cs
  src/amenities/docker-compose.test.yaml
Labels: Dev task

#171 Feature/task system/81512804
  .github/workflows/run-unit-tests.yml
  docker-compose/configs/nginx.conf
  docker-compose/docker-compose.dev.yaml
  docker-compose/docker-compose.yaml
  src/staff_webapp/package-lock.json
  src/staff_webapp/package.json
  src/staff_webapp/src/app/app.routes.ts
  src/staff_webapp/src/app/components/sidebar/sidebar.component.ts
  src/staff_webapp/src/app/components/task-modal/add-task-modal.component.html
  src/staff_webapp/src/app/components/task-modal/add-task-modal.component.ts
  src/staff_webapp/src/app/components/task-modal/confirm-deletion-modal.component.html
  src/staff_webapp/src/app/components/task-modal/confirm-deletion-modal.component.ts
  src/staff_webapp/src/app/components/task-modal/task-modal.component.html
  src/staff_webapp/src/app/components/task-modal/task-modal.component.ts
  src/staff_webapp/src/app/models/task-enums.ts
  src/staff_webapp/src/app/models/tasks.model.ts
  src/staff_webapp/src/app/pages/tasks-tab/mock-tasks.ts
  src/staff_webapp/src/app/pages/tasks-tab/tasks-tab.component.html
  src/staff_webapp/src/app/pages/tasks-tab/tasks-tab.component.spec.ts
  src/staff_webapp/src/app/pages/tasks-tab/tasks-tab.component.ts
  src/staff_webapp/src/app/services/task.service.spec.ts
  src/staff_webapp/src/app/services/task.service.ts
  src/staff_webapp/src/styles.css
  src/task_system/.dockerignore
  src/task_system/Dockerfile
  src/task_system/README.md
  src/task_system/configs/init.sql
  src/task_system/docker-compose.dev.yaml
  src/task_system/docker-compose.test.yaml
  src/task_system/docker-compose.yaml
  src/task_system/task_system.sln
  src/task_system/task_system_server/Controllers/TaskSystemController.cs
  src/task_system/task_system_server/Dtos/AddTaskDto.cs
  src/task_system/task_system_server/Dtos/UpdateTaskDto.cs
  src/task_system/task_system_server/Interfaces/ITaskSystemRepository.cs
  src/task_system/task_system_server/Mappers/TaskMapper.cs
  src/task_system/task_system_server/Models/QueryObject.cs
  src/task_system/task_system_server/Models/ResponseMessages.cs
  src/task_system/task_system_server/Models/TaskItem.cs
  src/task_system/task_system_server/Models/TaskSystemResponse.cs
  src/task_system/task_system_server/Persistences/TaskSystemDbContext.cs
  src/task_system/task_system_server/Program.cs
  src/task_system/task_system_server/Properties/launchSettings.json
  src/task_system/task_system_server/Repositories/PostgresTaskSystemRepository.cs
  src/task_system/task_system_server/Repositories/StubTaskSystemRepository.cs
  src/task_system/task_system_server/appsettings.Development.json
  src/task_system/task_system_server/appsettings.json
  src/task_system/task_system_server/task_system_server.csproj
  src/task_system/task_system_server/task_system_server.http
  src/task_system/task_system_test/PostgresTaskSystemRepositoryTest.cs
  src/task_system/task_system_test/StubTaskSystemRepositoryTest.cs
  src/task_system/task_system_test/TaskSystemControllerTest.cs
  src/task_system/task_system_test/task_system_test.csproj
Labels: Feature
